//! Reflection Entry - 反思记录

use super::classification::ErrorClassification;

/// A single reflection entry recording a failure and its resolution.
#[derive(Debug, Clone)]
pub struct ReflectionEntry {
    /// Timestamp when the reflection was created (ms since epoch).
    pub timestamp_ms: u64,
    /// The original action that failed.
    pub original_action: String,
    /// The error message received.
    pub error_message: String,
    /// Classification of the error.
    pub error_classification: ErrorClassification,
    /// The reflection/analysis generated by the agent.
    pub reflection_text: String,
    /// The alternative strategy attempted (if any).
    pub alternative_strategy: Option<String>,
    /// Whether the retry succeeded.
    pub resolved: bool,
    /// Number of retry attempts before success or final failure.
    pub retry_count: usize,
    /// Total time spent on retries (milliseconds).
    pub total_retry_duration_ms: u64,
}

impl ReflectionEntry {
    /// Create a new reflection entry.
    pub fn new(
        original_action: &str,
        error_message: &str,
        classification: ErrorClassification,
        reflection_text: &str,
    ) -> Self {
        Self {
            timestamp_ms: crate::types::now_millis(),
            original_action: original_action.to_string(),
            error_message: error_message.to_string(),
            error_classification: classification,
            reflection_text: reflection_text.to_string(),
            alternative_strategy: None,
            resolved: false,
            retry_count: 0,
            total_retry_duration_ms: 0,
        }
    }

    /// Mark this reflection as resolved with an alternative strategy.
    pub fn mark_resolved(&mut self, strategy: &str, retry_count: usize, duration_ms: u64) {
        self.alternative_strategy = Some(strategy.to_string());
        self.resolved = true;
        self.retry_count = retry_count;
        self.total_retry_duration_ms = duration_ms;
    }

    /// Get summary of this reflection entry.
    pub fn summary(&self) -> String {
        let status = if self.resolved {
            "✅ RESOLVED"
        } else {
            "❌ FAILED"
        };
        format!(
            "[{}] {} → {} (retries: {}, duration: {}ms)",
            status,
            self.original_action,
            self.error_classification.describe(),
            self.retry_count,
            self.total_retry_duration_ms
        )
    }
}
