//! Reflection Engine — Agent自我修正与智能重试系统
//!
//! Sprint 1-A3: 当执行失败时，Agent能够自动反思、修正策略并重试。
//!
//! ## 核心能力
//!
//! 1. **错误分类**: 区分可恢复错误（网络超时）和致命错误（权限不足）
//! 2. **智能重试**: 带指数退避的重试循环，避免无限循环
//! 3. **策略降级**: LLM推理 → 规则引擎 → 用户确认的多层降级
//! 4. **反思日志**: 记录每次失败的原因和修正措施，用于未来优化
//! 5. **替代方案生成**: 根据错误类型生成针对性的修复建议
//!
//! ## 架构
//!
//! ```text
//! Tool Execution Failed
//!     ↓
//! ReflectionEngine::analyze_error()
//!     ├─ ErrorClassification (Transient/Fatal/Permission/Invalid)
//!     └─ Confidence Score (0.0-1.0)
//!         ↓
//! ReflectionEngine::generate_reflection()
//!     ├─ What went wrong? (Root cause analysis)
//!     ├─ Why did it fail? (Context analysis)
//!     └─ How to fix it? (Alternative strategy)
//!         ↓
//! ReflectionEngine::execute_with_retry()
//!     ├─ Retry with backoff (if transient)
//!     ├─ Try alternative approach (if available)
//!     ├─ Degrade to fallback (if LLM fails)
//!     └─ Request user approval (if permission needed)
//! ```

use std::time::Duration;

// ===========================================================================
// Error Classification - 错误分类
// ===========================================================================

/// Classification of execution errors for appropriate response.
#[derive(Debug, Clone, PartialEq)]
pub enum ErrorClassification {
    /// Transient error that may succeed on retry (network timeout, rate limit).
    Transient {
        /// Suggested retry delay in milliseconds.
        retry_delay_ms: u64,
        /// Maximum number of retries recommended.
        max_retries: usize,
    },
    /// Fatal error that will not succeed without intervention (invalid parameters).
    Fatal {
        reason: String,
    },
    /// Permission error requiring user approval or privilege escalation.
    Permission {
        required_privilege: String,
        can_degrade: bool,
    },
    /// Invalid input error suggesting parameter adjustment.
    InvalidInput {
        parameter_name: String,
        suggestion: String,
    },
    /// Entity state error (not found, already exists, wrong type).
    EntityState {
        entity_name: String,
        expected_state: String,
        actual_state: String,
    },
}

impl ErrorClassification {
    /// Check if this error is recoverable through automatic means.
    pub fn is_auto_recoverable(&self) -> bool {
        matches!(
            self,
            ErrorClassification::Transient { .. }
                | ErrorClassification::InvalidInput { .. }
                | ErrorClassification::EntityState { .. }
                | ErrorClassification::Permission { can_degrade: true, .. }
        )
    }

    /// Check if this error requires user intervention.
    pub fn requires_user_intervention(&self) -> bool {
        matches!(self, ErrorClassification::Permission { can_degrade: false, .. })
    }

    /// Get human-readable description of this classification.
    pub fn describe(&self) -> String {
        match self {
            ErrorClassification::Transient { retry_delay_ms, max_retries } => {
                format!("Transient error (retry up to {}x with {}ms delay)", max_retries, retry_delay_ms)
            }
            ErrorClassification::Fatal { reason } => {
                format!("Fatal error: {}", reason)
            }
            ErrorClassification::Permission { required_privilege, can_degrade } => {
                if *can_degrade {
                    format!("Permission error (need '{}', can degrade to lower-risk approach)", required_privilege)
                } else {
                    format!("Permission error (requires '{}' from user)", required_privilege)
                }
            }
            ErrorClassification::InvalidInput { parameter_name, suggestion } => {
                format!("Invalid input for '{}': {}", parameter_name, suggestion)
            }
            ErrorClassification::EntityState { entity_name, expected_state, actual_state } => {
                format!("Entity '{}' state mismatch: expected {}, got {}",
                    entity_name, expected_state, actual_state)
            }
        }
    }
}

// ===========================================================================
// Reflection Entry - 反思记录
// ===========================================================================

/// A single reflection entry recording a failure and its resolution.
#[derive(Debug, Clone)]
pub struct ReflectionEntry {
    /// Timestamp when the reflection was created (ms since epoch).
    pub timestamp_ms: u64,
    /// The original action that failed.
    pub original_action: String,
    /// The error message received.
    pub error_message: String,
    /// Classification of the error.
    pub error_classification: ErrorClassification,
    /// The reflection/analysis generated by the agent.
    pub reflection_text: String,
    /// The alternative strategy attempted (if any).
    pub alternative_strategy: Option<String>,
    /// Whether the retry succeeded.
    pub resolved: bool,
    /// Number of retry attempts before success or final failure.
    pub retry_count: usize,
    /// Total time spent on retries (milliseconds).
    pub total_retry_duration_ms: u64,
}

impl ReflectionEntry {
    /// Create a new reflection entry.
    pub fn new(
        original_action: &str,
        error_message: &str,
        classification: ErrorClassification,
        reflection_text: &str,
    ) -> Self {
        Self {
            timestamp_ms: crate::types::now_millis(),
            original_action: original_action.to_string(),
            error_message: error_message.to_string(),
            error_classification: classification,
            reflection_text: reflection_text.to_string(),
            alternative_strategy: None,
            resolved: false,
            retry_count: 0,
            total_retry_duration_ms: 0,
        }
    }

    /// Mark this reflection as resolved with an alternative strategy.
    pub fn mark_resolved(&mut self, strategy: &str, retry_count: usize, duration_ms: u64) {
        self.alternative_strategy = Some(strategy.to_string());
        self.resolved = true;
        self.retry_count = retry_count;
        self.total_retry_duration_ms = duration_ms;
    }

    /// Get summary of this reflection entry.
    pub fn summary(&self) -> String {
        let status = if self.resolved { "✅ RESOLVED" } else { "❌ FAILED" };
        format!("[{}] {} → {} (retries: {}, duration: {}ms)",
            status,
            self.original_action,
            self.error_classification.describe(),
            self.retry_count,
            self.total_retry_duration_ms
        )
    }
}

// ===========================================================================
// Retry Configuration - 重试配置
// ===========================================================================

/// Configuration for retry behavior with exponential backoff.
#[derive(Debug, Clone)]
pub struct RetryConfig {
    /// Maximum number of retry attempts.
    pub max_retries: usize,
    /// Initial delay before first retry (milliseconds).
    pub initial_delay_ms: u64,
    /// Multiplier for delay between retries (exponential backoff).
    pub backoff_multiplier: f64,
    /// Maximum delay cap (milliseconds).
    pub max_delay_ms: u64,
    /// Whether to add jitter to prevent thundering herd.
    pub jitter: bool,
}

impl Default for RetryConfig {
    fn default() -> Self {
        Self {
            max_retries: 3,
            initial_delay_ms: 100,
            backoff_multiplier: 2.0,
            max_delay_ms: 5000,
            jitter: true,
        }
    }
}

impl RetryConfig {
    /// Calculate delay for a specific retry attempt (with optional jitter).
    pub fn calculate_delay(&self, attempt: usize) -> Duration {
        let base_delay = self.initial_delay_ms as f64
            * self.backoff_multiplier.powi(attempt as i32);
        let capped_delay = base_delay.min(self.max_delay_ms as f64) as u64;

        let final_delay = if self.jitter && capped_delay > 0 {
            // Add ±20% random jitter (simple implementation)
            let jitter_range = (capped_delay as f64 * 0.2) as u64;
            if jitter_range > 0 {
                // Use timestamp-based pseudo-random to avoid external dependency
                let pseudo_random = (crate::types::now_millis() % (jitter_range + 1)) as u64;
                capped_delay.saturating_add(pseudo_random)
            } else {
                capped_delay
            }
        } else {
            capped_delay
        };

        Duration::from_millis(final_delay as u64)
    }
}

// ===========================================================================
// Reflection Engine - 核心反思引擎
// ===========================================================================

/// Intelligent reflection engine for automatic error recovery and retry.
///
/// ## Usage
///
/// ```rust
/// # use agent_core::ReflectionEngine;
/// let mut engine = ReflectionEngine::new();
///
/// // Classify an error to determine recovery strategy:
/// let classification = engine.classify_error("Connection timed out");
/// assert!(classification.is_auto_recoverable());
///
/// // Generate a reflection analysis:
/// let reflection = engine.generate_reflection(
///     "create_entity",
///     "Connection timed out after 30s",
///     &classification,
/// );
/// assert!(reflection.contains("retry"));
/// ```
pub struct ReflectionEngine {
    /// Configuration for retry behavior.
    retry_config: RetryConfig,
    /// History of all reflections.
    reflection_history: Vec<ReflectionEntry>,
    /// Total number of successful reflections (for metrics).
    pub(crate) successful_reflections: usize,
    /// Total number of failed reflections (for metrics).
    pub(crate) failed_reflections: usize,
}

impl ReflectionEngine {
    /// Create a new ReflectionEngine with default configuration.
    pub fn new() -> Self {
        Self::with_config(RetryConfig::default())
    }

    /// Create a new ReflectionEngine with custom configuration.
    pub fn with_config(config: RetryConfig) -> Self {
        Self {
            retry_config: config,
            reflection_history: Vec::new(),
            successful_reflections: 0,
            failed_reflections: 0,
        }
    }

    /// Classify an error message into an appropriate category.
    ///
    /// Uses keyword matching and pattern recognition to determine
    /// the best course of action for handling the error.
    pub fn classify_error(&self, error: &str) -> ErrorClassification {
        let error_lower = error.to_lowercase();

        // === Transient Errors (Network/Timeout) ===
        if error_lower.contains("timeout") || error_lower.contains("超时")
            || error_lower.contains("timed out") || error_lower.contains("连接超时")
        {
            return ErrorClassification::Transient {
                retry_delay_ms: 500,
                max_retries: self.retry_config.max_retries,
            };
        }

        if error_lower.contains("connection refused") || error_lower.contains("连接被拒")
            || error_lower.contains("network error") || error_lower.contains("网络错误")
            || error_lower.contains("econnrefused") || error_lower.contains("etimedout")
        {
            return ErrorClassification::Transient {
                retry_delay_ms: 1000,
                max_retries: self.retry_config.max_retries,
            };
        }

        if error_lower.contains("rate limit") || error_lower.contains("速率限制")
            || error_lower.contains("too many requests") || error_lower.contains("请求过多")
            || error_lower.contains("429") || error_lower.contains("quota exceeded")
        {
            return ErrorClassification::Transient {
                retry_delay_ms: 2000,
                max_retries: self.retry_config.max_retries,
            };
        }

        // === Permission Errors ===
        if error_lower.contains("permission denied") || error_lower.contains("权限不足")
            || error_lower.contains("access denied") || error_lower.contains("拒绝访问")
            || error_lower.contains("unauthorized") || error_lower.contains("未授权")
            || error_lower.contains("403") || error_lower.contains("forbidden")
        {
            return ErrorClassification::Permission {
                required_privilege: "admin".into(),
                can_degrade: true,
            };
        }

        // === Entity State Errors ===
        if error_lower.contains("not found") || error_lower.contains("未找到")
            || error_lower.contains("does not exist") || error_lower.contains("不存在")
            || error_lower.contains("no such entity") || error_lower.contains("404")
        {
            let entity_name = extract_entity_from_error(error);
            return ErrorClassification::EntityState {
                entity_name,
                expected_state: "exists".into(),
                actual_state: "not found".into(),
            };
        }

        if error_lower.contains("already exists") || error_lower.contains("已存在")
            || error_lower.contains("duplicate") || error_lower.contains("重复")
            || error_lower.contains("409") || error_lower.contains("conflict")
        {
            let entity_name = extract_entity_from_error(error);
            return ErrorClassification::EntityState {
                entity_name,
                expected_state: "not exists".into(),
                actual_state: "already exists".into(),
            };
        }

        // === Invalid Input Errors ===
        if error_lower.contains("invalid") || error_lower.contains("无效")
            || error_lower.contains("parameter") || error_lower.contains("参数")
            || error_lower.contains("bad request") || error_lower.contains("400")
        {
            return ErrorClassification::InvalidInput {
                parameter_name: extract_parameter_name(error).unwrap_or_else(|| "unknown".into()),
                suggestion: "Check parameter values and types".into(),
            };
        }

        // === Default: Fatal Error ===
        ErrorClassification::Fatal {
            reason: truncate_str(error, 200),
        }
    }

    /// Generate a reflection text explaining what went wrong and how to fix it.
    ///
    /// This simulates the agent's reasoning process about the failure.
    pub fn generate_reflection(
        &self,
        original_action: &str,
        error: &str,
        classification: &ErrorClassification,
    ) -> String {
        let mut parts = Vec::new();

        parts.push(format!("**What went wrong?**"));
        parts.push(format!("Action '{}' failed with error: {}", original_action, truncate_str(error, 150)));

        parts.push(String::new());
        parts.push(format!("**Why did it fail?**"));
        match classification {
            ErrorClassification::Transient { .. } => {
                parts.push("This appears to be a temporary issue (network timeout, rate limiting).".into());
                parts.push("These errors often resolve themselves after a short wait.".into());
            }
            ErrorClassification::Fatal { reason } => {
                parts.push(format!("This is a fatal error that cannot be automatically recovered: {}", reason));
                parts.push("The operation cannot proceed without fundamental changes.".into());
            }
            ErrorClassification::Permission { required_privilege, can_degrade } => {
                parts.push(format!("Insufficient privileges: need '{}'", required_privilege));
                if *can_degrade {
                    parts.push("However, we may be able to use a lower-risk approach.".into());
                } else {
                    parts.push("User approval is required to proceed.".into());
                }
            }
            ErrorClassification::InvalidInput { parameter_name, suggestion } => {
                parts.push(format!("Parameter '{}' has invalid value", parameter_name));
                parts.push(format!("Suggestion: {}", suggestion));
            }
            ErrorClassification::EntityState { entity_name, expected_state, actual_state } => {
                parts.push(format!("Entity '{}' is in unexpected state", entity_name));
                parts.push(format!("Expected: {}, Actual: {}", expected_state, actual_state));
            }
        }

        parts.push(String::new());
        parts.push(format!("**How to fix it?**"));

        match classification {
            ErrorClassification::Transient { .. } => {
                parts.push("→ Wait briefly and retry the operation".into());
                parts.push("→ Use exponential backoff to avoid overwhelming the service".into());
            }
            ErrorClassification::Fatal { .. } => {
                parts.push("→ Abort this operation and report to user".into());
                parts.push("→ Suggest alternative approach if possible".into());
            }
            ErrorClassification::Permission { can_degrade, .. } => {
                if *can_degrade {
                    parts.push("→ Try a lower-risk approach that doesn't require elevated privileges".into());
                    parts.push("→ Request user confirmation for the degraded operation".into());
                } else {
                    parts.push("→ Request explicit user approval".into());
                    parts.push("→ Provide clear explanation of why permission is needed".into());
                }
            }
            ErrorClassification::InvalidInput { suggestion, .. } => {
                parts.push(format!("→ {}", suggestion));
                parts.push("→ Validate inputs before retrying".into());
            }
            ErrorClassification::EntityState { entity_name, actual_state, .. } => {
                if actual_state == "not found" {
                    parts.push(format!("→ Create entity '{}' first before operating on it", entity_name));
                } else if actual_state == "already exists" {
                    parts.push(format!("→ Skip creation and modify existing entity '{}'", entity_name));
                } else {
                    parts.push(format!("→ Adjust operation to account for current state of '{}'", entity_name));
                }
            }
        }

        parts.join("\n")
    }

    /// Generate an alternative strategy based on the error classification.
    ///
    /// Returns None if no alternative is available.
    pub fn generate_alternative_strategy(
        &self,
        original_action: &str,
        error: &str,
        classification: &ErrorClassification,
    ) -> Option<String> {
        let original_lower = original_action.to_lowercase();
        let _error_lower = error.to_lowercase();

        match classification {
            ErrorClassification::Transient { .. } => {
                Some(format!("Retry '{}' with exponential backoff", original_action))
            }

            ErrorClassification::Permission { can_degrade, .. } => {
                if *can_degrade {
                    Some(format!("[LOW_RISK] {} (degraded due to permission)", original_action))
                } else {
                    None
                }
            }

            ErrorClassification::EntityState { entity_name, actual_state, .. } => {
                if actual_state == "not found" {
                    if original_lower.contains("delete") || original_lower.contains("删除") {
                        Some(format!("Skip deletion of non-existent entity '{}'", entity_name))
                    } else if original_lower.contains("update") || original_lower.contains("修改")
                        || original_lower.contains("move") || original_lower.contains("移动")
                    {
                        Some(format!("Create entity '{}' first, then apply modification", entity_name))
                    } else {
                        Some(format!("Create missing entity '{}'", entity_name))
                    }
                } else if actual_state == "already exists" {
                if original_lower.contains("create") || original_lower.contains("创建")
                    || original_lower.contains("生成")
                {
                    let modified = if original_action.contains("Create") || original_action.contains("create") {
                        original_action.replace("Create", "Modify").replace("create", "modify")
                    } else if original_action.contains("创建") {
                        original_action.replace("创建", "修改")
                    } else if original_action.contains("生成") {
                        original_action.replace("生成", "更新")
                    } else {
                        format!("modify_entity('{}')", entity_name)
                    };
                    Some(modified)
                    } else {
                        Some(format!("Use existing entity '{}' instead of creating new one", entity_name))
                    }
                } else {
                    Some(format!("Adjust operation for entity '{}' in its current state", entity_name))
                }
            }

            ErrorClassification::InvalidInput { parameter_name, suggestion, .. } => {
                Some(format!("Fix parameter '{}': {}", parameter_name, suggestion))
            }

            ErrorClassification::Fatal { .. } => {
                None
            }
        }
    }

    /// Execute an operation with automatic retry and reflection.
    ///
    /// This is the main entry point for using the ReflectionEngine.
    ///
    /// # Type Parameters
    /// * `F` - Future-like type representing the async operation
    /// * `T` - Return type of the operation
    ///
    /// # Arguments
    /// * `operation` - Async function to execute (will be called multiple times on retry)
    /// * `action_name` - Human-readable name of the action (for logging)
    ///
    /// # Returns
    /// * `Ok(T)` - Operation succeeded (possibly after retries)
    /// * `Err(String)` - Operation failed after all retries or unrecoverable error
    #[allow(dead_code)] // Will be used once integrated
    pub async fn execute_with_retry<F, T, Fut>(
        &mut self,
        operation: F,
        action_name: &str,
    ) -> Result<T, String>
    where
        F: Fn() -> Fut,
        Fut: std::future::Future<Output = Result<T, String>>,
    {
        let mut last_error = String::new();
        let mut reflection_entry: Option<ReflectionEntry> = None;

        for attempt in 0..=self.retry_config.max_retries {
            // Attempt the operation
            match operation().await {
                Ok(result) => {
                    // Success!
                    if let Some(ref mut entry) = reflection_entry {
                        entry.mark_resolved(
                            &format!("Retry #{} succeeded", attempt),
                            attempt,
                            0, // Would need real timing here
                        );
                        self.reflection_history.push(entry.clone());
                        self.successful_reflections += 1;
                    }

                    eprintln!(
                        "[Reflection] Action '{}' succeeded on attempt {}/{}",
                        action_name,
                        attempt + 1,
                        self.retry_config.max_retries + 1
                    );

                    return Ok(result);
                }

                Err(error) => {
                    last_error = error.clone();

                    // Classify the error
                    let classification = self.classify_error(&error);

                    eprintln!(
                        "[Reflection] Action '{}' failed on attempt {}/{}: [{}] {}",
                        action_name,
                        attempt + 1,
                        self.retry_config.max_retries + 1,
                        classification.describe(),
                        truncate_str(&error, 100)
                    );

                    // Generate reflection (only on first failure)
                    if reflection_entry.is_none() {
                        let reflection_text = self.generate_reflection(action_name, &error, &classification);

                        reflection_entry = Some(ReflectionEntry::new(
                            action_name,
                            &error,
                            classification.clone(),
                            &reflection_text,
                        ));

                        eprintln!("[Reflection] Analysis:\n{}", reflection_text);
                    }

                    // Check if we should retry
                    if !classification.is_auto_recoverable() {
                        eprintln!(
                            "[Reflection] Non-recoverable error '{}', aborting",
                            classification.describe()
                        );
                        break;
                    }

                    // Check if we've exhausted retries
                    if attempt >= self.retry_config.max_retries {
                        eprintln!(
                            "[Reflection] Max retries ({}) reached",
                            self.retry_config.max_retries
                        );
                        break;
                    }

                    // Wait before retrying (exponential backoff)
                    let delay = self.retry_config.calculate_delay(attempt);
                    eprintln!(
                        "[Reflection] Waiting {:?} before retry #{}",
                        delay,
                        attempt + 1
                    );
                    tokio::time::sleep(delay).await;
                }
            }
        }

        // All retries exhausted or non-recoverable error
        if let Some(mut entry) = reflection_entry {
            entry.resolved = false;
            entry.retry_count = self.retry_config.max_retries + 1;
            self.reflection_history.push(entry.clone());
            self.failed_reflections += 1;
        }

        Err(format!(
            "Action '{}' failed after {} attempts: {}",
            action_name,
            self.retry_config.max_retries + 1,
            last_error
        ))
    }

    /// Get all reflection history entries.
    pub fn get_reflection_history(&self) -> &[ReflectionEntry] {
        &self.reflection_history
    }

    /// Get statistics about reflection performance.
    pub fn get_stats(&self) -> ReflectionStats {
        ReflectionStats {
            total_reflections: self.successful_reflections + self.failed_reflections,
            successful: self.successful_reflections,
            failed: self.failed_reflections,
            success_rate: if self.successful_reflections + self.failed_reflections > 0 {
                self.successful_reflections as f64
                    / (self.successful_reflections + self.failed_reflections) as f64
            } else {
                0.0
            },
        }
    }

    /// Clear reflection history (for testing or new session).
    pub fn clear_history(&mut self) {
        self.reflection_history.clear();
        self.successful_reflections = 0;
        self.failed_reflections = 0;
    }
}

impl Default for ReflectionEngine {
    fn default() -> Self {
        Self::new()
    }
}

// ===========================================================================
// Reflection Statistics
// ===========================================================================

/// Performance statistics for the reflection engine.
#[derive(Debug, Clone)]
pub struct ReflectionStats {
    /// Total number of reflections attempted.
    pub total_reflections: usize,
    /// Number of successful resolutions.
    pub successful: usize,
    /// Number of failures (all retries exhausted).
    pub failed: usize,
    /// Success rate (0.0 to 1.0).
    pub success_rate: f64,
}

impl std::fmt::Display for ReflectionStats {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "Reflections: total={}, ✅={}, ❌={}, rate={:.1}%",
            self.total_reflections, self.successful, self.failed,
            self.success_rate * 100.0
        )
    }
}

// ===========================================================================
// Helper Functions
// ===========================================================================

/// Extract entity name from error message.
fn extract_entity_from_error(error: &str) -> String {
    // Try single quotes: Entity 'Player'
    if let Some(start) = error.find('\'') {
        if let Some(end) = error[start + 1..].find('\'') {
            return error[start + 1..start + 1 + end].trim().to_string();
        }
    }

    // Try double quotes: Entity "Player"
    if let Some(start) = error.find('"') {
        if let Some(end) = error[start + 1..].find('"') {
            return error[start + 1..start + 1 + end].trim().to_string();
        }
    }

    "unknown".to_string()
}

/// Extract parameter name from error message.
fn extract_parameter_name(error: &str) -> Option<String> {
    let patterns = [
        "parameter '", "parameter \"",
        "argument '", "argument \"",
        "field '", "field \"",
        "value '", "value \"",
    ];

    for pattern in &patterns {
        if let Some(start) = error.find(pattern) {
            let after = &error[start + pattern.len()..];
            let name: String = after.chars()
                .take_while(|c| c.is_alphanumeric() || *c == '_')
                .collect();
            if !name.is_empty() {
                return Some(name);
            }
        }
    }

    None
}

/// Truncate string to max length with ellipsis.
fn truncate_str(s: &str, max_len: usize) -> String {
    if s.len() <= max_len {
        s.to_string()
    } else {
        format!("{}...", &s[..max_len])
    }
}

// ===========================================================================
// Tests
// ===========================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_reflection_engine_creation() {
        let engine = ReflectionEngine::new();
        assert_eq!(engine.get_reflection_history().len(), 0);
        assert_eq!(engine.get_stats().total_reflections, 0);
    }

    #[test]
    fn test_classify_transient_errors() {
        let engine = ReflectionEngine::new();

        let timeout = engine.classify_error("Operation timed out after 30s");
        assert!(matches!(timeout, ErrorClassification::Transient { .. }));

        let network = engine.classify_error("Connection refused: could not connect");
        assert!(matches!(network, ErrorClassification::Transient { .. }));

        let rate_limit = engine.classify_error("Rate limit exceeded, try again later");
        assert!(matches!(rate_limit, ErrorClassification::Transient { .. }));
    }

    #[test]
    fn test_classify_permission_errors() {
        let engine = ReflectionEngine::new();

        let perm = engine.classify_error("Permission denied: requires admin role");
        assert!(matches!(perm, ErrorClassification::Permission { can_degrade: true, .. }));
        assert!(perm.is_auto_recoverable());

        let unauthorized = engine.classify_error("Unauthorized access to resource");
        assert!(matches!(unauthorized, ErrorClassification::Permission { .. }));
    }

    #[test]
    fn test_classify_entity_state_errors() {
        let engine = ReflectionEngine::new();

        let not_found = engine.classify_error("Entity 'Player' not found");
        match not_found {
            ErrorClassification::EntityState { entity_name, .. } => {
                assert_eq!(entity_name, "Player");
            }
            other => unreachable!("Expected EntityState, got {:?}", other),
        }

        let exists = engine.classify_error("Entity 'Boss' already exists");
        match exists {
            ErrorClassification::EntityState { actual_state, .. } => {
                assert_eq!(actual_state, "already exists");
            }
            other => unreachable!("Expected EntityState, got {:?}", other),
        }
    }

    #[test]
    fn test_classify_invalid_input_errors() {
        let engine = ReflectionEngine::new();

        let invalid = engine.classify_error("Invalid parameter 'color': must be RGBA array");
        match invalid {
            ErrorClassification::InvalidInput { parameter_name, .. } => {
                assert_eq!(parameter_name, "color");
            }
            other => unreachable!("Expected InvalidInput, got {:?}", other),
        }
    }

    #[test]
    fn test_classify_fatal_errors() {
        let engine = ReflectionEngine::new();

        let fatal = engine.classify_error("Internal assertion failed: null pointer dereference");
        assert!(matches!(fatal, ErrorClassification::Fatal { .. }));
        assert!(!fatal.is_auto_recoverable());
    }

    #[test]
    fn test_generate_reflection_for_timeout() {
        let engine = ReflectionEngine::new();
        let classification = ErrorClassification::Transient {
            retry_delay_ms: 500,
            max_retries: 3,
        };

        let reflection = engine.generate_reflection(
            "call_api",
            "Request timed out after 30s",
            &classification,
        );

        assert!(reflection.contains("What went wrong?"));
        assert!(reflection.contains("temporary"));
        assert!(reflection.contains("How to fix it?"));
        assert!(reflection.contains("retry"));
    }

    #[test]
    fn test_generate_alternative_for_not_found() {
        let engine = ReflectionEngine::new();
        let classification = ErrorClassification::EntityState {
            entity_name: "Enemy".into(),
            expected_state: "exists".into(),
            actual_state: "not found".into(),
        };

        let alt = engine.generate_alternative_strategy(
            "delete_entity('Enemy')",
            "Entity 'Enemy' not found",
            &classification,
        );

        assert!(alt.is_some(), "Should generate alternative for not-found entity");
        let alt_text = alt.unwrap();
        assert!(
            alt_text.contains("non-existent") || alt_text.contains("skip"),
            "Alternative should handle deletion of non-existent entity"
        );
    }

    #[test]
    fn test_generate_alternative_for_already_exists() {
        let engine = ReflectionEngine::new();
        let classification = ErrorClassification::EntityState {
            entity_name: "Player".into(),
            expected_state: "not exists".into(),
            actual_state: "already exists".into(),
        };

        let alt = engine.generate_alternative_strategy(
            "create_entity('Player')",
            "Entity 'Player' already exists",
            &classification,
        );

        assert!(alt.is_some(), "Should generate alternative for duplicate entity");
        let alt_text = alt.unwrap();
        assert!(
            alt_text.contains("Modify") || alt_text.contains("modify"),
            "Alternative should change creation to modification"
        );
    }

    #[test]
    fn test_retry_config_backoff_calculation() {
        let config = RetryConfig {
            max_retries: 3,
            initial_delay_ms: 100,
            backoff_multiplier: 2.0,
            max_delay_ms: 1000,
            jitter: false,
        };

        let delay0 = config.calculate_delay(0);
        let delay1 = config.calculate_delay(1);
        let delay2 = config.calculate_delay(2);

        assert_eq!(delay0, Duration::from_millis(100));
        assert_eq!(delay1, Duration::from_millis(200));
        assert_eq!(delay2, Duration::from_millis(400)); // Not yet capped
    }

    #[test]
    fn test_retry_config_max_delay_cap() {
        let config = RetryConfig {
            max_retries: 10,
            initial_delay_ms: 100,
            backoff_multiplier: 10.0,
            max_delay_ms: 500,
            jitter: false,
        };

        let delay2 = config.calculate_delay(2); // 100 * 10^2 = 10000 → capped at 500
        assert_eq!(delay2, Duration::from_millis(500));
    }

    #[test]
    fn test_reflection_entry_summary() {
        let mut entry = ReflectionEntry::new(
            "create_player",
            "Timeout error",
            ErrorClassification::Transient {
                retry_delay_ms: 100,
                max_retries: 3,
            },
            "Test reflection text",
        );

        assert!(!entry.resolved);
        assert_eq!(entry.retry_count, 0);

        entry.mark_resolved("Retry succeeded", 2, 250);

        assert!(entry.resolved);
        assert_eq!(entry.retry_count, 2);

        let summary = entry.summary();
        assert!(summary.contains("✅ RESOLVED"));
        assert!(summary.contains("create_player"));
    }

    #[test]
    fn test_stats_tracking() {
        let mut engine = ReflectionEngine::new();

        // Simulate some reflections
        engine.successful_reflections = 8;
        engine.failed_reflections = 2;

        let stats = engine.get_stats();
        assert_eq!(stats.total_reflections, 10);
        assert_eq!(stats.successful, 8);
        assert_eq!(stats.failed, 2);
        assert!((stats.success_rate - 0.8).abs() < 0.01, "Success rate should be ~80%");
    }

    #[test]
    fn test_extract_entity_from_error() {
        assert_eq!(extract_entity_from_error("Entity 'Player' not found"), "Player");
        assert_eq!(extract_entity_from_error("Entity \"Boss\" already exists"), "Boss");
        assert_eq!(extract_entity_from_error("No entity mentioned"), "unknown");
    }

    #[test]
    fn test_error_classification_descriptions() {
        let transient = ErrorClassification::Transient {
            retry_delay_ms: 100,
            max_retries: 3,
        };
        assert!(transient.describe().contains("Transient"));
        assert!(transient.describe().contains("retry"));

        let fatal = ErrorClassification::Fatal {
            reason: "Test error".into(),
        };
        assert!(fatal.describe().contains("Fatal"));

        let permission = ErrorClassification::Permission {
            required_privilege: "admin".into(),
            can_degrade: true,
        };
        assert!(permission.describe().contains("Permission"));
        assert!(permission.describe().contains("degrade"));
    }
}
